// Advanced14.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"
#include <iostream>
using namespace std;

int main()
{
	//delcare constants
	const int ORC_PRICE = 25;
	const int MF_PRICE = 30;
	const int BALC_PRICE = 15;

	//declare variables
	int orcTickets = 0;
	int mfTickets = 0;
	int balcTickets = 0;
	int orcRev = 0;
	int mfRev = 0;
	int balcRev = 0;
	int totalRev = 0;
	double orcPercTotal = 0;
	double mfPercTotal = 0;
	double balcPercTotal = 0;

	//user is prompted to input number of tickets sold for each seating category
	cout << "Please enter the number of orchestra seat tickets sold: ";
	cin >> orcTickets;
	cout << "Please enter the number of main floor tickets sold: ";
	cin >> mfTickets;
	cout << "Please enter the number of balcony seat tickets sold: ";
	cin >> balcTickets;
	cout << endl;

	//revenue for each ticket type is calculated, as well as total revenue
	orcRev = orcTickets*ORC_PRICE;
	mfRev = mfTickets*MF_PRICE;
	balcRev = balcTickets*BALC_PRICE;
	totalRev = orcRev + mfRev + balcRev;

	//calculates revenue contributed by each 
	//seating category as a percent of total revenue
	orcPercTotal = static_cast<float>(orcRev) / totalRev * 100;
	mfPercTotal = static_cast<float>(mfRev) / totalRev * 100;
	balcPercTotal = static_cast<float>(balcRev) / totalRev * 100;

	//revenue for each ticket type and total revenue are displayed
	cout << "Revenue generated by orchestra ticket sales: $" << orcRev << endl;
	cout << "Percentage of total revenue: " << orcPercTotal << "%" << endl << endl;
	cout << "Revenue generated by main floor ticket sales: $" << mfRev << endl;
	cout << "Percentage of total revenue: " << mfPercTotal << "%" << endl << endl;
	cout << "Revenue generated by balcony ticket sales: $" << balcRev << endl;
	cout << "Percentage of total revenue: " << balcPercTotal << "%" << endl << endl;
	cout << "Total revenue generated: $" << totalRev << endl << endl;

	system("pause");

	return 0;
}

